backend:
  name: github
  repo: exodevhub/exodevhub-website

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: img, label: Image, widget: image}
      - { name: title, label: Title }
      - { name: category, label: Category }
      - { name: shape, label: Shape }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author, widget: markdown }
  - name: people
    label: People
    folder: people
    create: true
    fields:
      - { name: img, label: Image, widget: image}
      - { name: title, label: Title }
      - { name: twitter, label: Twitter }
      - { name: github, label: Github }


